import type { BusinessVerticalDefinition } from '../../types/verticals.types';

export const DIETETICA_NATURISTA_PRESET: BusinessVerticalDefinition = {
  id: 'DIETETICA_NATURISTA',
  name: 'Dietética & Tienda Naturista',
  icon: 'bi-egg-fried',
  description: 'Frutos secos, harinas integrales, semillas, té en hebras, productos sin gluten y veganos.',
  bannerTitle: 'Alimentación Consciente, Sana & Natural',
  bannerSubtitle: 'Frutos secos seleccionados, alimentos sin TACC, superalimentos orgánicos y suplementación natural.',
  heroImages: [
    'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=1920&h=700&fit=crop&q=80',
    'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=1920&h=700&fit=crop&q=80',
  ],
  featuredCategories: [
    { categoryId: 'frutos-secos', name: 'Frutos Secos', slug: 'frutos-secos', imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'sin-tacc', name: 'Sin TACC & Celíacos', slug: 'sin-tacc', imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'superalimentos', name: 'Superalimentos', slug: 'superalimentos', imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'infusiones', name: 'Té & Infusiones', slug: 'infusiones', imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&h=400&fit=crop&q=80' },
  ],
  categories: [
    { id: 'frutos-secos', name: 'Frutos Secos, Semillas & Frutas Deshidratadas', slug: 'frutos-secos', order: 1, filterableAttributes: ['peso-gr'] },
    { id: 'harinas-cereales', name: 'Harinas Integrales, Avenas & Legumbres', slug: 'harinas-cereales', order: 2, filterableAttributes: ['peso-gr'] },
    { id: 'sin-tacc', name: 'Productos Sin TACC Certificados', slug: 'sin-tacc', order: 3, filterableAttributes: [] },
    { id: 'superalimentos', name: 'Superfoods, Maca, Espirulina & Proteínas Veganas', slug: 'superalimentos', order: 4, filterableAttributes: [] },
    { id: 'infusiones', name: 'Té en Hebras, Hierbas Medicinales & Miel', slug: 'infusiones', order: 5, filterableAttributes: [] },
    { id: 'aceites-untables', name: 'Mantecas de Frutos Secos & Aceites Prensados', slug: 'aceites-untables', order: 6, filterableAttributes: [] },
  ],
  attributes: [
    { id: 'peso-gr', name: 'Peso', code: 'peso-gr', type: 'button', values: ['250 g', '500 g', '1 kg'], required: false },
  ],
  colors: {
    primary: '#65a30d',
    accent: '#d97706',
    background: '#ffffff',
  },
  featureCards: [
    { title: 'Alimentos Puros y Sin Aditivos', content: 'Frutos secos frescos de cosecha reciente y harinas molidas a la piedra.' },
    { title: 'Línea Sin TACC Certificada', content: 'Variedad de productos aptos para celíacos y dietas plant-based.' },
    { title: 'A Granel y Fraccionado', content: 'Comprá la cantidad exacta que necesitás con packaging resellable hermético.' },
  ],
  sampleProducts: [
    {
      name: 'Nueces Chandler Peladas Mariposa Extra Light 500g',
      categorySlug: 'frutos-secos',
      price: 13500,
      stock: 50,
      skuPrefix: 'DIE-NUC-500',
      description: 'Cosecha fresca del Valle de Uco, mitades enteras seleccionadas ricas en omega 3 y antioxidantes.',
      image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Almendras Nonpareil Calibre Grande 500g',
      categorySlug: 'frutos-secos',
      price: 14800,
      stock: 45,
      skuPrefix: 'DIE-ALM-500',
      description: 'Almendras dulces crudas sin tostar de piel suave y alto contenido de magnesio y vitamina E.',
      image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Castañas de Cajú Tostadas Sin Sal 500g',
      categorySlug: 'frutos-secos',
      price: 16900,
      stock: 35,
      skuPrefix: 'DIE-CAJ-500',
      description: 'Castañas enteras w320 de sabor suave y mantecoso tostadas en su punto justo.',
      image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Mix de Semillas Activables (Chía, Lino, Sésamo y Girasol) 500g',
      categorySlug: 'frutos-secos',
      price: 6500,
      stock: 60,
      skuPrefix: 'DIE-SEM-500',
      description: 'Mezcla balanceada de semillas limpias ideales para agregar a panes, ensaladas y yogures.',
      image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Avena Arrollada Tradicional Gruesa Orgánica 1kg',
      categorySlug: 'harinas-cereales',
      price: 4900,
      stock: 80,
      skuPrefix: 'DIE-AVN-1KG',
      description: 'Hojuelas de avena 100% integral sin aditivos para porridge, granolas y repostería saludable.',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Harina de Almendras Pura Desgrasada Fina 500g',
      categorySlug: 'harinas-cereales',
      price: 12500,
      stock: 40,
      skuPrefix: 'DIE-HAR-ALM',
      description: '100% harina de almendras peladas molidas a la piedra, apta para dietas Keto, Low Carb y Sin TACC.',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Quinoa Real Orgánica Perlada Lavada 500g',
      categorySlug: 'harinas-cereales',
      price: 7800,
      stock: 55,
      skuPrefix: 'DIE-QUN-500',
      description: 'Grano andino libre de saponina listo para cocinar con alto contenido de proteína vegetal completa.',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Premix Universal Sin Gluten para Panadería y Repostería 1kg',
      categorySlug: 'sin-tacc',
      price: 5900,
      stock: 70,
      skuPrefix: 'DIE-PRM-ST',
      description: 'Mezcla certificada libre de gluten con fécula de mandioca, almidón de maíz y harina de arroz.',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Pasta Seca Fusilli Sin TACC de Maíz y Arroz 500g',
      categorySlug: 'sin-tacc',
      price: 4800,
      stock: 65,
      skuPrefix: 'DIE-FUS-ST',
      description: 'Fideos libres de gluten que mantienen su estructura al dente sin desarmarse al hervir.',
      image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Galletitas Dulces Sin TACC con Chips de Chocolate 200g',
      categorySlug: 'sin-tacc',
      price: 4200,
      stock: 60,
      skuPrefix: 'DIE-GLT-ST',
      description: 'Cookies crujientes elaboradas en planta exclusiva libre de gluten con cacao puro.',
      image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Espirulina Pura Orgánica en Polvo Superfood 150g',
      categorySlug: 'superalimentos',
      price: 18500,
      stock: 35,
      skuPrefix: 'DIE-ESP-150',
      description: 'Microalga unicelular rica en clorofila, hierro biodisponible y 65% de proteínas vegetales.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Maca Peruana Negra en Polvo Gelatinizada 200g',
      categorySlug: 'superalimentos',
      price: 19800,
      stock: 30,
      skuPrefix: 'DIE-MAC-200',
      description: 'Adaptógeno natural de alta absorción que incrementa la energía, resistencia y balance hormonal.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Proteína Vegetal Vegana de Arvejas & Arroz Aislada 500g',
      categorySlug: 'superalimentos',
      price: 28000,
      stock: 30,
      skuPrefix: 'DIE-PRO-VEG',
      description: '24g de proteína por porción sabor vainilla natural sin azúcar, sin soja y libre de lácteos.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Semillas de Chía Orgánicas Negras de Altura 500g',
      categorySlug: 'superalimentos',
      price: 6900,
      stock: 75,
      skuPrefix: 'DIE-CHI-500',
      description: 'Excelente fuente de fibra soluble y ácidos grasos omega 3 para pudines, batidos y panificados.',
      image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Té Verde Matcha Japonés Ceremonial Grado Premium 50g',
      categorySlug: 'infusiones',
      price: 24000,
      stock: 35,
      skuPrefix: 'DIE-MAT-50G',
      description: 'Hojas de té verde de sombra molidas finamente a la piedra con alto poder antioxidante EGCG.',
      image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Blend de Té en Hebras Frutos Rojos & Hibisco 100g',
      categorySlug: 'infusiones',
      price: 9500,
      stock: 50,
      skuPrefix: 'DIE-TE-FRT',
      description: 'Mezcla aromática de flores de hibisco, arándanos deshidratados, frutillas y pétalos de rosas.',
      image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Miel Pura de Pradera Agroecológica Frasco 1kg',
      categorySlug: 'infusiones',
      price: 9800,
      stock: 60,
      skuPrefix: 'DIE-MEL-1KG',
      description: 'Miel cruda sin calentar ni pasteurizar cosechada artesanalmente preservando enzimas y polen natural.',
      image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Pasta de Maní 100% Natural Tostado sin Azúcar ni Sal 500g',
      categorySlug: 'aceites-untables',
      price: 6200,
      stock: 80,
      skuPrefix: 'DIE-PAS-MAN',
      description: 'Un solo ingrediente: maní argentino tostado molido hasta lograr textura cremosa sedosa.',
      image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Aceite de Coco Virgen Prensado en Frío Orgánico 500ml',
      categorySlug: 'aceites-untables',
      price: 14500,
      stock: 45,
      skuPrefix: 'DIE-OIL-COC',
      description: 'Aroma fresco natural a coco con ácidos grasos MCT para cocción saludable, café y cuidado corporal.',
      image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cacao Amargo Puro 100% Alcalino en Polvo 250g',
      categorySlug: 'harinas-cereales',
      price: 8900,
      stock: 55,
      skuPrefix: 'DIE-CAC-250',
      description: 'Sabor profundo a chocolate sin azúcar agregada para desayunos saludables y repostería fitness.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Levadura Nutricional en Copos con Vitamina B12 150g',
      categorySlug: 'superalimentos',
      price: 11000,
      stock: 50,
      skuPrefix: 'DIE-LEV-B12',
      description: 'Condimento sabor queso sin lácteos enriquecido con vitamina B12 para dietas veganas y vegetarianas.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
  ],
};
