import type { BusinessVerticalDefinition } from '../../types/verticals.types';

export const IMPRENTA_MERCHANDISING_PRESET: BusinessVerticalDefinition = {
  id: 'IMPRENTA_MERCHANDISING',
  name: 'Imprenta & Merchandising',
  icon: 'bi-printer',
  description: 'Impresión digital, folletos, cartelería, tazas personalizadas, remeras corporativas y packaging.',
  bannerTitle: 'Soluciones Gráficas, Merchandising & Packaging',
  bannerSubtitle: 'Impresión offset y digital de alta definición, regalos corporativos y cartelería comercial.',
  heroImages: [
    'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1920&h=700&fit=crop&q=80',
    'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=1920&h=700&fit=crop&q=80',
  ],
  featuredCategories: [
    { categoryId: 'grafica-comercial', name: 'Gráfica Comercial', slug: 'grafica-comercial', imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'merchandising', name: 'Merchandising & Regalos', slug: 'merchandising', imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'indumentaria-corp', name: 'Remeras & Uniformes', slug: 'indumentaria-corp', imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'packaging', name: 'Packaging & Etiquetas', slug: 'packaging', imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&h=400&fit=crop&q=80' },
  ],
  categories: [
    { id: 'grafica-comercial', name: 'Folletos, Tarjetas & Papelería Comercial', slug: 'grafica-comercial', order: 1, filterableAttributes: ['cantidad-pack'] },
    { id: 'merchandising', name: 'Tazas, Botellas & Regalos Corporativos', slug: 'merchandising', order: 2, filterableAttributes: [] },
    { id: 'indumentaria-corp', name: 'Remeras, Gorras & Uniformes Estampados', slug: 'indumentaria-corp', order: 3, filterableAttributes: ['talle-imprenta'] },
    { id: 'packaging', name: 'Bolsas Kraft, Cajas & Etiquetas Adhesivas', slug: 'packaging', order: 4, filterableAttributes: ['cantidad-pack'] },
    { id: 'carteleria-banners', name: 'Banners, Vinilos & Cartelería Gran Formato', slug: 'carteleria-banners', order: 5, filterableAttributes: [] },
  ],
  attributes: [
    { id: 'cantidad-pack', name: 'Cantidad / Tirada', code: 'cantidad-pack', type: 'select', values: ['Pack x100 unidades', 'Pack x500 unidades', 'Pack x1000 unidades'], required: false },
    { id: 'talle-imprenta', name: 'Talle', code: 'talle-imprenta', type: 'button', values: ['S', 'M', 'L', 'XL', 'XXL'], required: false },
  ],
  sampleProducts: [
    {
      name: 'Tarjetas Personales Premium Laminado Mate 350g (Pack x500)',
      categorySlug: 'grafica-comercial',
      price: 28000,
      stock: 50,
      skuPrefix: 'IMP-TRJ-500',
      description: 'Impresión offset full color frente y dorso en cartulina ilustración pesada con laca UV sectorizada.',
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Folletos Flyers A5 Full Color Ilustración 150g (Pack x1000)',
      categorySlug: 'grafica-comercial',
      price: 49000,
      stock: 35,
      skuPrefix: 'IMP-FLY-1000',
      description: 'Medida 15x21cm impresos en alta definición ideales para promociones comerciales y eventos.',
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Carpetas Institucionales con Solapa Portatarjetas (Pack x100)',
      categorySlug: 'grafica-comercial',
      price: 64000,
      stock: 25,
      skuPrefix: 'IMP-CARP-100',
      description: 'Cartulina encapada 300g con cuño para tarjeta personal y solapa pegada para hojas A4.',
      image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Taza de Cerámica Importada Blanca Sublimada Full Color',
      categorySlug: 'merchandising',
      price: 8500,
      stock: 80,
      skuPrefix: 'IMP-TAZ-SUB',
      description: 'Apta para microondas y lavavajillas con impresión fotográfica 360° nítida y brillante.',
      image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Botella Deportiva Térmica Aluminio 600ml con Logo Grabado Láser',
      categorySlug: 'merchandising',
      price: 18500,
      stock: 45,
      skuPrefix: 'IMP-BOT-LSR',
      description: 'Grabado permanente inalterable con acabado mate antideslizante y mosquetón de transporte.',
      image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cuaderno Corporativo A5 Tapa Dura Ecocuero con Logo Grabado',
      categorySlug: 'merchandising',
      price: 16500,
      stock: 50,
      skuPrefix: 'IMP-LIB-CORP',
      description: '80 hojas rayadas de 80g con elástico de cierre, cinta señaladora y grabado bajorrelieve.',
      image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Bolígrafos Metálicos con Grabado Láser de Marca (Pack x50)',
      categorySlug: 'merchandising',
      price: 36000,
      stock: 40,
      skuPrefix: 'IMP-PEN-50',
      description: 'Cuerpo metálico con grip gomoso, clip cromado y tinta fluida de larga duración.',
      image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Remera de Algodón Peinado 24/1 con Serigrafía / DTF',
      categorySlug: 'indumentaria-corp',
      price: 24500,
      stock: 60,
      skuPrefix: 'IMP-REM-DTF',
      description: 'Estampado textil de alta resistencia al lavado en remera de corte unisex reforzada.',
      image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'IMP-REM-M', price: 24500, stock: 30, attributes: { 'talle-imprenta': 'M' } },
        { sku: 'IMP-REM-L', price: 24500, stock: 30, attributes: { 'talle-imprenta': 'L' } },
      ],
    },
    {
      name: 'Gorra Trucker con Frente Acolchado y Logo Bordado / Estampado',
      categorySlug: 'indumentaria-corp',
      price: 14000,
      stock: 55,
      skuPrefix: 'IMP-CAP-TRK',
      description: 'Malla plástica respirable trasera con broche regulable snapback de 7 posiciones.',
      image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Buzo Hoodie Canguro Frisado con Bordado Institucional',
      categorySlug: 'indumentaria-corp',
      price: 52000,
      stock: 30,
      skuPrefix: 'IMP-HD-BRD',
      description: 'Frisa pesada de primera calidad con bordado computarizado de alta definición en pecho o manga.',
      image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'IMP-HD-L', price: 52000, stock: 15, attributes: { 'talle-imprenta': 'L' } },
        { sku: 'IMP-HD-XL', price: 52000, stock: 15, attributes: { 'talle-imprenta': 'XL' } },
      ],
    },
    {
      name: 'Bolsas de Papel Kraft con Manijas de Cordón (Pack x100)',
      categorySlug: 'packaging',
      price: 34000,
      stock: 45,
      skuPrefix: 'IMP-BAG-KRF',
      description: 'Papel kraft marrón ecológico de 120g con base reforzada para locales de indumentaria y regalos.',
      image: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Stickers Autoadhesivos Troquelados en Vinilo (Pack x500)',
      categorySlug: 'packaging',
      price: 26000,
      stock: 60,
      skuPrefix: 'IMP-STK-VIN',
      description: 'Vinilo impermeable resistente al agua y sol con semicorte troquelado según la forma de tu logo.',
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cajas de Envíos Ecommerce Automontables Microcorrugado (Pack x50)',
      categorySlug: 'packaging',
      price: 42000,
      stock: 40,
      skuPrefix: 'IMP-BOX-ECO',
      description: 'Cartón resistente para envíos por correo con traba de seguridad lateral sin necesidad de cinta extra.',
      image: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cinta de Embalar Impresa Personalizada con Logo 48mm x 100m (Pack x6)',
      categorySlug: 'packaging',
      price: 29000,
      stock: 35,
      skuPrefix: 'IMP-CNT-EMB',
      description: 'Adhesivo acrílico de alta adherencia con impresión a 2 colores para seguridad de paquetes.',
      image: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Banner Roll-Up Autoenrollable de Aluminio 85x200cm con Lona',
      categorySlug: 'carteleria-banners',
      price: 68000,
      stock: 20,
      skuPrefix: 'IMP-BNR-ROL',
      description: 'Estructura retráctil liviana de aluminio con lona front de alta resolución y bolso de transporte incluido.',
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cartel de Chapa Plegada / PVC Espumado 100x50cm Impreso',
      categorySlug: 'carteleria-banners',
      price: 45000,
      stock: 25,
      skuPrefix: 'IMP-CRT-PVC',
      description: 'Sustrato rígido para señalética de locales y oficinas con vinilo laminado anti-rayaduras UV.',
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Vinilo Microperforado para Vidrieras Comerciales (Metro Cuadrado)',
      categorySlug: 'carteleria-banners',
      price: 22000,
      stock: 40,
      skuPrefix: 'IMP-VIN-MIC',
      description: 'Permite visibilidad total desde el interior hacia afuera mostrando la gráfica publicitaria desde la calle.',
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Tote Bag de Lienzo de Algodón Crudo Estampada',
      categorySlug: 'merchandising',
      price: 7800,
      stock: 75,
      skuPrefix: 'IMP-TOT-LNZ',
      description: 'Bolsa ecológica reutilizable de 40x40cm con manijas reforzadas y estampa serigráfica.',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Llaveros Acrílicos Personalizados con Forma Especial (Pack x100)',
      categorySlug: 'merchandising',
      price: 24000,
      stock: 45,
      skuPrefix: 'IMP-LLV-ACR',
      description: 'Acrílico cristal de 3mm cortado por láser con impresión digital directa UV doble faz.',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Credenciales de PVC Tipo Tarjeta de Crédito con Cordón (Pack x50)',
      categorySlug: 'grafica-comercial',
      price: 32000,
      stock: 30,
      skuPrefix: 'IMP-CRD-PVC',
      description: 'Credenciales plásticas durables con código de barras o QR para eventos corporativos y acreditaciones.',
      image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cinta Colgante Lanyard Satinada con Mosquetón (Pack x50)',
      categorySlug: 'merchandising',
      price: 19500,
      stock: 50,
      skuPrefix: 'IMP-LAN-SAT',
      description: 'Cinta de 20mm estampada por sublimación continua full color en ambos lados.',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
  ],
};
