import type { BusinessVerticalDefinition } from '../../types/verticals.types';

export const LIBRERIA_PAPELERIA_PRESET: BusinessVerticalDefinition = {
  id: 'LIBRERIA_PAPELERIA',
  name: 'Librería & Papelería',
  icon: 'bi-journal-bookmark',
  description: 'Cuadernos de diseño, artículos de arte, escritura fina, útiles escolares y libros.',
  bannerTitle: 'Inspiración, Creatividad y Escritura',
  bannerSubtitle: 'Papelería de autor, materiales para artistas, libros seleccionados e insumos de oficina.',
  heroImages: [
    'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1920&h=700&fit=crop&q=80',
    'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=1920&h=700&fit=crop&q=80',
  ],
  featuredCategories: [
    { categoryId: 'cuadernos', name: 'Cuadernos & Agendas', slug: 'cuadernos', imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'escritura', name: 'Escritura & Plumas', slug: 'escritura', imageUrl: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'arte', name: 'Arte & Dibujo', slug: 'arte', imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'organizacion', name: 'Oficina & Mochilas', slug: 'organizacion', imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=400&fit=crop&q=80' },
  ],
  categories: [
    { id: 'cuadernos', name: 'Cuadernos, Agendas & Bullet Journals', slug: 'cuadernos', order: 1, filterableAttributes: ['hojas'] },
    { id: 'escritura', name: 'Bolígrafos, Rollers & Plumas Fuente', slug: 'escritura', order: 2, filterableAttributes: ['trazo'] },
    { id: 'arte', name: 'Acuarelas, Marcadores & Dibujo Pro', slug: 'arte', order: 3, filterableAttributes: [] },
    { id: 'escolar', name: 'Útiles Escolares & Manualidades', slug: 'escolar', order: 4, filterableAttributes: [] },
    { id: 'organizacion', name: 'Mochilas, Cartucheras & Oficina', slug: 'organizacion', order: 5, filterableAttributes: [] },
  ],
  attributes: [
    { id: 'hojas', name: 'Interior de Hojas', code: 'hojas', type: 'select', values: ['Rayadas', 'Punteadas (Bullet)', 'Cuadriculadas', 'Lisas'], required: false },
    { id: 'trazo', name: 'Grosor de Trazo', code: 'trazo', type: 'button', values: ['Fino 0.5mm', 'Medio 0.7mm', 'Grueso 1.0mm'], required: false },
  ],
  colors: {
    primary: '#4f46e5',
    accent: '#f43f5e',
    background: '#ffffff',
  },
  featureCards: [
    { title: 'Papel de Alto Gramaje', content: 'Cuadernos y bitácoras resistentes a tintas al agua y plumas estilográficas.' },
    { title: 'Marcas de Arte Internacionales', content: 'Insumos profesionales para ilustración, caligrafía y lettering.' },
    { title: 'Packaging Cuidadoso', content: 'Tus libros y libretas llegan impecables sin esquinas dobladas ni marcas.' },
  ],
  sampleProducts: [
    {
      name: 'Cuaderno Tapa Dura Bullet Journal 120g Punteado A5',
      categorySlug: 'cuadernos',
      price: 18500,
      stock: 45,
      skuPrefix: 'LIB-CD-BJ',
      description: '192 páginas de papel libre de ácido de 120g que no traspasa la tinta. Tapa dura encuadernada en ecocuero.',
      image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'LIB-CD-BJ-DOT', price: 18500, stock: 25, attributes: { hojas: 'Punteadas (Bullet)' } },
        { sku: 'LIB-CD-BJ-LIN', price: 18500, stock: 20, attributes: { hojas: 'Rayadas' } },
      ],
    },
    {
      name: 'Agenda Semanal 2026 Tapa Dura con Planner Mensual',
      categorySlug: 'cuadernos',
      price: 24000,
      stock: 35,
      skuPrefix: 'LIB-AG26',
      description: 'Planificador anual con cinta señaladora, sobre fuelle trasero y hojas de stickers temáticos.',
      image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cuaderno Universitario Espiral Doble Alambre 100 Hojas',
      categorySlug: 'cuadernos',
      price: 8900,
      stock: 70,
      skuPrefix: 'LIB-UNI',
      description: 'Hojas microperforadas con margen reforzado y tapas de polipropileno de alta resistencia.',
      image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Libreta de Bolsillo Pocket 9x14cm (Pack x3)',
      categorySlug: 'cuadernos',
      price: 12000,
      stock: 50,
      skuPrefix: 'LIB-PCK',
      description: 'Libretas flexibles de costura visible con papel kraft natural ideales para llevar a todos lados.',
      image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Pluma Estilográfica Premium con Pluma de Acero Inoxidable',
      categorySlug: 'escritura',
      price: 36000,
      stock: 25,
      skuPrefix: 'LIB-PLU',
      description: 'Cuerpo metálico laqueado con convertidor de émbolo para tinta en tintero y cartuchos universales.',
      image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Rollerball de Gel Borrable Fricción 0.7mm (Set x4 Colores)',
      categorySlug: 'escritura',
      price: 14500,
      stock: 60,
      skuPrefix: 'LIB-ROL-BOR',
      description: 'Tinta termosensible que se borra por fricción sin dañar el papel ni dejar residuos.',
      image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Set de Microfibras Graduadas Fineliner (Estuche x8)',
      categorySlug: 'escritura',
      price: 22000,
      stock: 40,
      skuPrefix: 'LIB-FIN-8',
      description: 'Puntas calibradas de 0.05mm a 0.8mm con tinta pigmentada impermeable resistente a la luz.',
      image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Bolígrafo Retráctil de Metal con Grip Texturado',
      categorySlug: 'escritura',
      price: 9500,
      stock: 55,
      skuPrefix: 'LIB-PEN-MET',
      description: 'Mecanismo de click suave con repuesto de tinta de aceite fluida de secado instantáneo.',
      image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'LIB-PEN-05', price: 9500, stock: 30, attributes: { trazo: 'Fino 0.5mm' } },
        { sku: 'LIB-PEN-07', price: 9500, stock: 25, attributes: { trazo: 'Medio 0.7mm' } },
      ],
    },
    {
      name: 'Set de Marcadores de Alcohol Doble Punta Art (Caja x48)',
      categorySlug: 'arte',
      price: 49000,
      stock: 25,
      skuPrefix: 'LIB-MRK-ALC',
      description: 'Marcadores profesionales con punta pincel flexible y biselada para ilustración, manga y bocetos.',
      image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Caja de Acuarelas en Pastilla Calidad Artista 24 Colores',
      categorySlug: 'arte',
      price: 38000,
      stock: 20,
      skuPrefix: 'LIB-ACU-24',
      description: 'Pigmentos puros de alta solubilidad y transparencia en caja metálica con paleta de mezcla y pincel de agua.',
      image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Block de Papel para Acuarela 300g 100% Algodón A4 20 Hojas',
      categorySlug: 'arte',
      price: 26000,
      stock: 30,
      skuPrefix: 'LIB-BLK-ACU',
      description: 'Prensado en frío con grano fino, encolado en los 4 lados para evitar deformaciones con el agua.',
      image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Lápices de Color Policromos Graduados (Lata x36)',
      categorySlug: 'arte',
      price: 42000,
      stock: 25,
      skuPrefix: 'LIB-LAP-36',
      description: 'Minas gruesas a base de cera de 3.8mm con máxima resistencia a la rotura y cobertura uniforme.',
      image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Mochila Urbana Portanotebook Impermeable 20L',
      categorySlug: 'organizacion',
      price: 58000,
      stock: 30,
      skuPrefix: 'LIB-MCH-NB',
      description: 'Compartimento acolchado para laptop de 15.6", puerto de carga USB externo y espaldar ergonómico.',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cartuchera Desplegable Tipo Canopla Multicompartimento',
      categorySlug: 'organizacion',
      price: 16500,
      stock: 45,
      skuPrefix: 'LIB-CAR-MUL',
      description: 'Capacidad para 50 útiles con elásticos organizadores para marcadores, regla y tijera.',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Organizador de Escritorio Metálico Malla Mesh 5 Divisiones',
      categorySlug: 'organizacion',
      price: 19800,
      stock: 35,
      skuPrefix: 'LIB-ORG-MET',
      description: 'Porta lápices, tacos de notas, clips y bandeja porta documentos integrada.',
      image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Set de Resaltadores Pastel Soft (Blister x6 Colores)',
      categorySlug: 'escolar',
      price: 9800,
      stock: 80,
      skuPrefix: 'LIB-RST-PAS',
      description: 'Punta biselada de 2 y 5mm con tinta a base de agua que no mancha el reverso de las fotocopias.',
      image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Notas Adhesivas Tipo Post-it Pastel 76x76mm (Pack x4)',
      categorySlug: 'escolar',
      price: 5900,
      stock: 90,
      skuPrefix: 'LIB-NOT-ADH',
      description: 'Adhesivo reposicionable que no deja marcas en libros, cuadernos o pantallas de monitor.',
      image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Abrochadora Metálica de Mesa + 1000 Broches 24/6',
      categorySlug: 'organizacion',
      price: 13500,
      stock: 40,
      skuPrefix: 'LIB-ABR-MET',
      description: 'Capacidad de abrochado de hasta 30 hojas de 80g con base antideslizante de goma.',
      image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Tijera Escolar Soft Grip Acero Inoxidable 17cm',
      categorySlug: 'escolar',
      price: 4900,
      stock: 85,
      skuPrefix: 'LIB-TIJ-SFT',
      description: 'Mangos ergonómicos con goma antifatiga y hojas afiladas con punta redondeada de seguridad.',
      image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cinta Correctora en Cinta Ergonómica 5mm x 12m',
      categorySlug: 'escolar',
      price: 3800,
      stock: 90,
      skuPrefix: 'LIB-COR-CNT',
      description: 'Aplicación en seco que permite reescribir inmediatamente sin manchas.',
      image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Set de Washi Tape Cintas Decorativas Japonesas (Caja x10)',
      categorySlug: 'arte',
      price: 11500,
      stock: 45,
      skuPrefix: 'LIB-WSH-10',
      description: 'Cintas de papel de arroz adhesivas removibles para journaling, scrapbooking y manualidades.',
      image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
  ],
};
