import type { BusinessVerticalDefinition } from '../../types/verticals.types';

export const PET_SHOP_VETERINARIA_PRESET: BusinessVerticalDefinition = {
  id: 'PET_SHOP_VETERINARIA',
  name: 'Pet Shop & Veterinaria',
  icon: 'bi-heart-pulse',
  description: 'Alimento premium, juguetes, camas, paseadores, higiene y accesorios para mascotas.',
  bannerTitle: 'El Mejor Cuidado y Amor para tu Mascota',
  bannerSubtitle: 'Nutrición de alta gama, accesorios confortables y productos de salud veterinaria.',
  heroImages: [
    'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=1920&h=700&fit=crop&q=80',
    'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=1920&h=700&fit=crop&q=80',
  ],
  featuredCategories: [
    { categoryId: 'perros-alimento', name: 'Alimento para Perros', slug: 'perros-alimento', imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'gatos-alimento', name: 'Alimento para Gatos', slug: 'gatos-alimento', imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'accesorios-paseo', name: 'Paseo & Correas', slug: 'accesorios-paseo', imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'camas-confort', name: 'Camas & Rascadores', slug: 'camas-confort', imageUrl: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=600&h=400&fit=crop&q=80' },
  ],
  categories: [
    { id: 'perros-alimento', name: 'Perros - Alimento & Snacks', slug: 'perros-alimento', order: 1, filterableAttributes: ['peso-bolsa'] },
    { id: 'gatos-alimento', name: 'Gatos - Alimento & Golosinas', slug: 'gatos-alimento', order: 2, filterableAttributes: ['peso-bolsa'] },
    { id: 'accesorios-paseo', name: 'Arneses, Collares & Paseo', slug: 'accesorios-paseo', order: 3, filterableAttributes: ['talle-mascota'] },
    { id: 'camas-confort', name: 'Camas, Cuevas & Rascadores', slug: 'camas-confort', order: 4, filterableAttributes: ['talle-mascota'] },
    { id: 'higiene-salud', name: 'Higiene, Antiparasitarios & Salud', slug: 'higiene-salud', order: 5, filterableAttributes: [] },
  ],
  attributes: [
    { id: 'peso-bolsa', name: 'Peso', code: 'peso-bolsa', type: 'button', values: ['3 kg', '7.5 kg', '15 kg', '20 kg'], required: false },
    { id: 'talle-mascota', name: 'Talle', code: 'talle-mascota', type: 'button', values: ['S (Pequeño)', 'M (Mediano)', 'L (Grande)', 'XL (Gigante)'], required: false },
  ],
  colors: {
    primary: '#0284c7',
    accent: '#f59e0b',
    background: '#ffffff',
  },
  featureCards: [
    { title: 'Nutrición Super Premium', content: 'Las mejores marcas de balanceados recomendadas por veterinarios.' },
    { title: 'Snacks y Juguetes Seguros', content: 'Materiales no tóxicos y libres de químicos nocivos para mascotas.' },
    { title: 'Despacho Rápido', content: 'No te quedes sin alimento: envíos ágiles a la puerta de tu casa.' },
  ],
  sampleProducts: [
    {
      name: 'Alimento Perro Adulto Raza Mediana & Grande Super Premium 15kg',
      categorySlug: 'perros-alimento',
      price: 62000,
      stock: 40,
      skuPrefix: 'PET-DOG-AD',
      description: 'Proteínas de pollo de alto valor biológico, prebióticos y glucosamina para salud articular.',
      image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Alimento Perro Cachorro Puppy Growth Formula 15kg',
      categorySlug: 'perros-alimento',
      price: 68000,
      stock: 35,
      skuPrefix: 'PET-DOG-PUP',
      description: 'Enriquecido con DHA para desarrollo cognitivo, calcio y fósforo balanceados para crecimiento óseo óptimo.',
      image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Alimento Perro Senior 7+ Control de Peso 15kg',
      categorySlug: 'perros-alimento',
      price: 64000,
      stock: 25,
      skuPrefix: 'PET-DOG-SNR',
      description: 'Bajo en calorías con L-carnitina, antioxidantes y condroitina para perros mayores.',
      image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Snacks Dentales para Perro Clean Teeth (Pack x14)',
      categorySlug: 'perros-alimento',
      price: 9500,
      stock: 60,
      skuPrefix: 'PET-SNK-DNT',
      description: 'Barritas masticables con textura estriada que reducen el sarro y combaten el mal aliento.',
      image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Alimento Gato Adulto Castrado Urinario Care 7.5kg',
      categorySlug: 'gatos-alimento',
      price: 45000,
      stock: 40,
      skuPrefix: 'PET-CAT-STR',
      description: 'Control de pH urinario, fibras naturales anti-bolas de pelo y contenido calórico moderado.',
      image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Alimento Gato Kitten Cachorro Salmón & Arroz 3kg',
      categorySlug: 'gatos-alimento',
      price: 26000,
      stock: 30,
      skuPrefix: 'PET-CAT-KIT',
      description: 'Croquetas pequeñas de fácil masticación ricas en omega 3 y taurina esencial para gatitos.',
      image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Snacks Cremosos para Gatos Sabor Atún & Salmón (Pack x4)',
      categorySlug: 'gatos-alimento',
      price: 4900,
      stock: 90,
      skuPrefix: 'PET-CAT-TRT',
      description: 'Puré húmedo irresistible con alto contenido de agua y vitaminas para premiar e hidratar.',
      image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Arnés Antitirones Acolchado Regulable para Perros',
      categorySlug: 'accesorios-paseo',
      price: 28000,
      stock: 45,
      skuPrefix: 'PET-ARN',
      description: 'Diseño ergonómico con enganche frontal en el pecho, reflectivo 3M y manija de control rápido.',
      image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'PET-ARN-M', price: 28000, stock: 25, attributes: { 'talle-mascota': 'M (Mediano)' } },
        { sku: 'PET-ARN-L', price: 32000, stock: 20, attributes: { 'talle-mascota': 'L (Grande)' } },
      ],
    },
    {
      name: 'Correa Extensible Retráctil Automática 5m con Freno',
      categorySlug: 'accesorios-paseo',
      price: 22000,
      stock: 35,
      skuPrefix: 'PET-COR-RET',
      description: 'Cinta de nylon resistente de 5 metros para perros de hasta 30kg con botón de bloqueo ergonómico.',
      image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Collar de Cuero Genuino Reforzado con Placa de Identificación',
      categorySlug: 'accesorios-paseo',
      price: 19500,
      stock: 30,
      skuPrefix: 'PET-COL',
      description: 'Costuras dobles con hebilla metálica de acero niquelado inoxidable.',
      image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cama Nido Antiestrés Redonda Pelo Largo Ultrasuave',
      categorySlug: 'camas-confort',
      price: 36000,
      stock: 30,
      skuPrefix: 'PET-BED-RLX',
      description: 'Relleno de vellón siliconado hipoalergénico con base impermeable antideslizante lavable.',
      image: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'PET-BED-M', price: 36000, stock: 15, attributes: { 'talle-mascota': 'M (Mediano)' } },
        { sku: 'PET-BED-L', price: 46000, stock: 15, attributes: { 'talle-mascota': 'L (Grande)' } },
      ],
    },
    {
      name: 'Cama Colchón Ortopédico Espuma Memory Foam',
      categorySlug: 'camas-confort',
      price: 52000,
      stock: 20,
      skuPrefix: 'PET-BED-ORT',
      description: 'Alivia la presión articular de perros grandes y ancianos con funda impermeable desmontable.',
      image: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Rascador Torre para Gatos Multinivel 1.40m con Cueva',
      categorySlug: 'camas-confort',
      price: 68000,
      stock: 15,
      skuPrefix: 'PET-SCR-TWR',
      description: 'Postes forrados en sisal natural de 6mm con plataformas acolchadas y juguetes colgantes.',
      image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Piedras Sanitarias Aglomerantes para Gatos 10kg',
      categorySlug: 'higiene-salud',
      price: 12500,
      stock: 70,
      skuPrefix: 'PET-SND',
      description: 'Bentonita natural que forma grumos compactos instantáneos y neutraliza olores con aroma a lavanda.',
      image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Shampoo Hipoalergénico con Aloe Vera & Avena 500ml',
      categorySlug: 'higiene-salud',
      price: 13500,
      stock: 50,
      skuPrefix: 'PET-SHP',
      description: 'pH neutro especial para piel sensible de perros y gatos, libre de parabenos y colorantes.',
      image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Pipeta Antiparasitaria Pulgas & Garrapatas Perro',
      categorySlug: 'higiene-salud',
      price: 14000,
      stock: 80,
      skuPrefix: 'PET-PIP',
      description: 'Protección integral por 30 días contra pulgas, garrapatas y mosquitos transmisores de leishmaniasis.',
      image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'PET-PIP-M', price: 14000, stock: 40, attributes: { 'talle-mascota': 'M (Mediano)' } },
        { sku: 'PET-PIP-L', price: 16500, stock: 40, attributes: { 'talle-mascota': 'L (Grande)' } },
      ],
    },
    {
      name: 'Comedero & Bebedero Doble de Acero con Soporte Elevado',
      categorySlug: 'camas-confort',
      price: 24500,
      stock: 35,
      skuPrefix: 'PET-BOWL',
      description: 'Estructura de bambú ecológico que mejora la postura digestiva al comer.',
      image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Juguete Mordillo de Caucho Natural Ultra Resistente',
      categorySlug: 'perros-alimento',
      price: 11000,
      stock: 55,
      skuPrefix: 'PET-TOY-KNG',
      description: 'Juguete rellenable con alimento o pasta para estimulación mental y alivio de ansiedad.',
      image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Cardina Cepillo Deslanador Quita Pelo Muerto',
      categorySlug: 'higiene-salud',
      price: 16000,
      stock: 45,
      skuPrefix: 'PET-BRS',
      description: 'Cerdas de acero inoxidable con punta protegida y botón de autolimpieza rápida.',
      image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Bolso Transportador Aprobado para Cabina de Avión',
      categorySlug: 'accesorios-paseo',
      price: 49000,
      stock: 20,
      skuPrefix: 'PET-TRN',
      description: 'Estructura rígida plegable con malla transpirable de ventilación 360° y correa al hombro.',
      image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Fuente de Agua Eléctrica para Mascotas 2.5L Filtro Carbón',
      categorySlug: 'camas-confort',
      price: 34000,
      stock: 25,
      skuPrefix: 'PET-FNT',
      description: 'Bomba ultrasilenciosa con filtración cuádruple de agua para incentivar la hidratación felina y canina.',
      image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
  ],
};
