import type { BusinessVerticalDefinition } from '../../types/verticals.types';

export const TECNOLOGIA_ELECTRONICA_PRESET: BusinessVerticalDefinition = {
  id: 'TECNOLOGIA_ELECTRONICA',
  name: 'Tecnología & Electrónica',
  icon: 'bi-laptop',
  description: 'Smartphones, notebooks, gaming, periféricos, audio y electrodomésticos.',
  bannerTitle: 'Tecnología de Vanguardia y Gadgets',
  bannerSubtitle: 'Equipos, periféricos y accesorios de alto rendimiento con garantía oficial.',
  heroImages: [
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1920&h=700&fit=crop&q=80',
    'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1920&h=700&fit=crop&q=80',
  ],
  featuredCategories: [
    { categoryId: 'smartphones', name: 'Smartphones', slug: 'smartphones', imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'laptops', name: 'Notebooks', slug: 'notebooks', imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'audio', name: 'Audio Hi-Fi', slug: 'audio', imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'electro', name: 'Electrodomésticos', slug: 'electrodomesticos', imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&h=400&fit=crop&q=80' },
  ],
  categories: [
    { id: 'smartphones', name: 'Smartphones & Wearables', slug: 'smartphones', order: 1, filterableAttributes: ['almacenamiento', 'color'] },
    { id: 'laptops', name: 'Notebooks & Computación', slug: 'notebooks', order: 2, filterableAttributes: ['ram', 'almacenamiento', 'color'] },
    { id: 'audio', name: 'Audio & Auriculares', slug: 'audio', order: 3, filterableAttributes: ['color', 'conectividad'] },
    { id: 'perifericos', name: 'Teclados & Periféricos', slug: 'perifericos', order: 4, filterableAttributes: ['switch', 'color'] },
    { id: 'electro', name: 'Electrodomésticos & Smart Home', slug: 'electrodomesticos', order: 5, filterableAttributes: ['color', 'voltaje'] },
  ],
  attributes: [
    { id: 'color', name: 'Color', code: 'color', type: 'color', values: ['Negro Matte', 'Plata Titanio', 'Azul Marino', 'Blanco Glaciar'], required: true },
    { id: 'almacenamiento', name: 'Almacenamiento', code: 'almacenamiento', type: 'button', values: ['128 GB', '256 GB', '512 GB', '1 TB'], required: true },
    { id: 'ram', name: 'Memoria RAM', code: 'ram', type: 'button', values: ['8 GB', '16 GB', '32 GB'], required: true },
    { id: 'conectividad', name: 'Conectividad', code: 'conectividad', type: 'select', values: ['Bluetooth 5.3', 'Inalámbrico 2.4GHz', 'USB-C'], required: false },
    { id: 'switch', name: 'Tipo de Switch', code: 'switch', type: 'select', values: ['Red Lineal', 'Brown Táctil', 'Blue Clicky'], required: false },
    { id: 'voltaje', name: 'Voltaje', code: 'voltaje', type: 'select', values: ['220V', 'Dual 110V/220V'], required: false },
  ],
  sampleProducts: [
    {
      name: 'Smartphone Pro Ultra 5G (256GB / 512GB)',
      categorySlug: 'smartphones',
      price: 1250000,
      stock: 35,
      skuPrefix: 'SP-ULTRA',
      description: 'Pantalla OLED 6.7" 120Hz, cámara triple de 200MP, procesador Octa-Core y batería de 5000mAh.',
      image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'SP-ULTRA-256-BLK', price: 1250000, stock: 20, attributes: { almacenamiento: '256 GB', color: 'Negro Matte' } },
        { sku: 'SP-ULTRA-512-SLV', price: 1450000, stock: 15, attributes: { almacenamiento: '512 GB', color: 'Plata Titanio' } },
      ],
      brand: 'Vertex Tech',
    },
    {
      name: 'Notebook Pro Developer 16" M-Chip',
      categorySlug: 'notebooks',
      price: 2450000,
      stock: 18,
      skuPrefix: 'NB-DEV16',
      description: 'Arquitectura ultra eficiente de 12 núcleos, pantalla Liquid Retina XDR y hasta 22h de autonomía.',
      image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'NB-DEV16-16-512', price: 2450000, stock: 10, attributes: { ram: '16 GB', almacenamiento: '512 GB', color: 'Plata Titanio' } },
        { sku: 'NB-DEV16-32-1TB', price: 2950000, stock: 8, attributes: { ram: '32 GB', almacenamiento: '1 TB', color: 'Negro Matte' } },
      ],
      brand: 'NexGen',
    },
    {
      name: 'Auriculares ANC Hi-Res Wireless',
      categorySlug: 'audio',
      price: 185000,
      stock: 40,
      skuPrefix: 'AUD-ANC',
      description: 'Cancelación activa de ruido inteligente, audio espacial 360° y 40 horas de reproducción.',
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop&q=80',
      hasVariants: true,
      variants: [
        { sku: 'AUD-ANC-BLK', price: 185000, stock: 25, attributes: { color: 'Negro Matte', conectividad: 'Bluetooth 5.3' } },
        { sku: 'AUD-ANC-WHT', price: 185000, stock: 15, attributes: { color: 'Blanco Glaciar', conectividad: 'Bluetooth 5.3' } },
      ],
      brand: 'Acoustic Labs',
    },
    {
      name: 'Cafetera Espresso Smart Automática 19 Bar',
      categorySlug: 'electrodomesticos',
      price: 320000,
      stock: 12,
      skuPrefix: 'EL-COFFEE',
      description: 'Bomba italiana de 19 bares con molinillo cónico integrado y control térmico PID.',
      image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
      brand: 'Vertex Home',
    },
  ],
};
