import type { BusinessVerticalDefinition } from '../../types/verticals.types';

export const VIVEROS_JARDINERIA_PRESET: BusinessVerticalDefinition = {
  id: 'VIVEROS_JARDINERIA',
  name: 'Viveros & Jardinería',
  icon: 'bi-tree',
  description: 'Plantas de interior, macetas de diseño, sustratos orgánicos, fertilizantes y huerta.',
  bannerTitle: 'Espacios Verdes, Naturaleza & Vida en tu Hogar',
  bannerSubtitle: 'Plantas aclimatadas, macetas autorriego, insumos para huerta urbana y herramientas de jardinería.',
  heroImages: [
    'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=1920&h=700&fit=crop&q=80',
    'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1920&h=700&fit=crop&q=80',
  ],
  featuredCategories: [
    { categoryId: 'plantas-interior', name: 'Plantas de Interior', slug: 'plantas-interior', imageUrl: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'macetas-deco', name: 'Macetas & Jardineras', slug: 'macetas-deco', imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'sustratos-abonos', name: 'Sustratos & Abonos', slug: 'sustratos-abonos', imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop&q=80' },
    { categoryId: 'huerta-semillas', name: 'Huerta & Semillas', slug: 'huerta-semillas', imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d69102a5c?w=600&h=400&fit=crop&q=80' },
  ],
  categories: [
    { id: 'plantas-interior', name: 'Plantas de Interior & Follaje', slug: 'plantas-interior', order: 1, filterableAttributes: ['luz-requerida'] },
    { id: 'plantas-exterior', name: 'Plantas de Exterior, Arbustos & Flores', slug: 'plantas-exterior', order: 2, filterableAttributes: ['luz-requerida'] },
    { id: 'macetas-deco', name: 'Macetas de Cemento, Cerámica & Rotomoldeo', slug: 'macetas-deco', order: 3, filterableAttributes: ['material-maceta'] },
    { id: 'sustratos-abonos', name: 'Sustratos, Compost & Fertilizantes', slug: 'sustratos-abonos', order: 4, filterableAttributes: [] },
    { id: 'huerta-semillas', name: 'Semillas Orgánicas, Huerta & Riego', slug: 'huerta-semillas', order: 5, filterableAttributes: [] },
    { id: 'herramientas-jardin', name: 'Herramientas & Accesorios de Poda', slug: 'herramientas-jardin', order: 6, filterableAttributes: [] },
  ],
  attributes: [
    { id: 'luz-requerida', name: 'Requerimiento de Luz', code: 'luz-requerida', type: 'select', values: ['Luz Indirecta Brillante', 'Poca Luz / Sombra', 'Sol Directo Pleno'], required: false },
    { id: 'material-maceta', name: 'Material de Maceta', code: 'material-maceta', type: 'select', values: ['Cerámica Esmaltada', 'Cemento Artesanal', 'Plástico Rotomoldeado Ligero', 'Barro Natural Cocido'], required: false },
  ],
  colors: {
    primary: '#15803d',
    accent: '#84cc16',
    background: '#ffffff',
  },
  featureCards: [
    { title: 'Plantas Sanas y Aclimatadas', content: 'Cultivo cuidado con sustratos orgánicos y control biológico de plagas.' },
    { title: 'Embalaje con Protección Hídrica', content: 'Enviamos tus ejemplares con protección hídrica y fijación de cepellón.' },
    { title: 'Guía de Cuidados Personalizada', content: 'Cada planta incluye una ficha con sus requerimientos específicos de riego y luz.' },
  ],
  sampleProducts: [
    {
      name: 'Monstera Deliciosa Costilla de Adán en Maceta de 20cm',
      categorySlug: 'plantas-interior',
      price: 28000,
      stock: 25,
      skuPrefix: 'VIV-PLN-MON',
      description: 'Hojas grandes fenestradas icónicas de fácil cuidado para interiores luminosos con riego moderado.',
      image: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Ficus Lyrata Higuera de Hoja de Violín 1.20m',
      categorySlug: 'plantas-interior',
      price: 64000,
      stock: 15,
      skuPrefix: 'VIV-PLN-FIC',
      description: 'Árbol ornamental de interior de hojas lustrosas en forma de lira en maceta de cultivo reforzada.',
      image: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Sansevieria Trifasciata Lengua de Suegra en Maceta',
      categorySlug: 'plantas-interior',
      price: 19500,
      stock: 40,
      skuPrefix: 'VIV-PLN-SAN',
      description: 'Planta purificadora de aire altamente resistente que tolera poca luz y riegos espaciados.',
      image: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Pothos Dorado Colgante Epipremnum Aureum',
      categorySlug: 'plantas-interior',
      price: 16000,
      stock: 35,
      skuPrefix: 'VIV-PLN-POT',
      description: 'Enredadera de hojas acorazonadas variegadas con crecimiento rápido para repisas o macetas colgantes.',
      image: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Calathea Orbiculata Hojas Gigantes Rayadas',
      categorySlug: 'plantas-interior',
      price: 32000,
      stock: 20,
      skuPrefix: 'VIV-PLN-CAL',
      description: 'Follaje decorativo con patrones plateados que pliega sus hojas al caer la noche (planta de oración).',
      image: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Strelitzia Reginae Flor de Pájaro en Maceta Grande',
      categorySlug: 'plantas-exterior',
      price: 58000,
      stock: 18,
      skuPrefix: 'VIV-PLN-STR',
      description: 'Planta tropical majestuosa de exterior o sol pleno con flores anaranjadas y azules espectaculares.',
      image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Lavanda Francesa Aromática en Maceta 3 Litros',
      categorySlug: 'plantas-exterior',
      price: 14500,
      stock: 45,
      skuPrefix: 'VIV-PLN-LAV',
      description: 'Arbusto perenne con espigas florales violetas muy perfumadas que atraen polinizadores y repelen plagas.',
      image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Jazmín del Cabo Gardenia Perfumado en Flor',
      categorySlug: 'plantas-exterior',
      price: 36000,
      stock: 20,
      skuPrefix: 'VIV-PLN-JAZ',
      description: 'Flores blancas carnosas de aroma dulce inconfundible con follaje verde oscuro brillante.',
      image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Maceta Rotomoldeada Cilíndrica Texturada 40cm con Plato',
      categorySlug: 'macetas-deco',
      price: 34000,
      stock: 30,
      skuPrefix: 'VIV-MAC-ROT',
      description: 'Polietileno virgen irrompible con protección anti-UV de peso ultraliviano para interior y exterior.',
      image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Maceta de Cerámica Esmaltada Artesanal Nude 22cm',
      categorySlug: 'macetas-deco',
      price: 24000,
      stock: 35,
      skuPrefix: 'VIV-MAC-CER',
      description: 'Terminación satinada mate hecha a mano en torno con orificio de drenaje y plato desmontable.',
      image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Pie Porta Macetas Trípode Madera de Paraíso Macizo 50cm',
      categorySlug: 'macetas-deco',
      price: 22500,
      stock: 30,
      skuPrefix: 'VIV-PIE-PAR',
      description: 'Soporte nórdico elevado para macetas de hasta 25cm de diámetro con hidrolaqueado antihumedad.',
      image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Sustrato Profesional Premium para Plantas de Interior 20 Litros',
      categorySlug: 'sustratos-abonos',
      price: 13500,
      stock: 60,
      skuPrefix: 'VIV-SUS-20L',
      description: 'Mezcla aireada con turba de Sphagnum, perlita expandida, corteza de pino y humus de lombriz.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Humus de Lombriz Californiana 100% Orgánico 10 Litros',
      categorySlug: 'sustratos-abonos',
      price: 8900,
      stock: 70,
      skuPrefix: 'VIV-HUM-10L',
      description: 'Fertilizante biológico rico en flora microbiana benéfica que mejora la estructura y nutrición del suelo.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Fertilizante Foliar Bioestimulante Algas Marinas 250ml',
      categorySlug: 'sustratos-abonos',
      price: 12000,
      stock: 50,
      skuPrefix: 'VIV-FER-ALG',
      description: 'Extracto natural de Ascophyllum Nodosum que estimula el enraizamiento y la resistencia al estrés hídrico.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Aceite de Neem Puro + Jabón Potásico Insecticida Orgánico 500ml',
      categorySlug: 'sustratos-abonos',
      price: 11500,
      stock: 65,
      skuPrefix: 'VIV-NEM-POT',
      description: 'Control preventivo y curativo 100% natural contra pulgones, cochinillas, trips y mosca blanca.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Kit de Cultivo Huerta Urbana en Casa (6 Variedades)',
      categorySlug: 'huerta-semillas',
      price: 29000,
      stock: 35,
      skuPrefix: 'VIV-KIT-HRT',
      description: 'Incluye cajón de madera tratado, sustrato fértil, macetas biodegradables, semillas de albahaca, rúcula, tomate cherry y guía.',
      image: 'https://images.unsplash.com/photo-1592417817098-8f3d69102a5c?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Regadera de Diseño de Acero Inoxidable y Mango de Madera 1.5L',
      categorySlug: 'herramientas-jardin',
      price: 26000,
      stock: 40,
      skuPrefix: 'VIV-REG-INOX',
      description: 'Pico largo y fino que permite dirigir el agua con precisión a la raíz sin salpicar el follaje.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Tijera de Poda Bypass de Precisión Acero Japonés SK5',
      categorySlug: 'herramientas-jardin',
      price: 24500,
      stock: 35,
      skuPrefix: 'VIV-TIJ-SK5',
      description: 'Corte limpio y preciso para ramas verdes de hasta 20mm con cierre de seguridad y resorte suave.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Set de 3 Herramientas Manuales para Jardín (Pala, Rastrillo y Trasplantador)',
      categorySlug: 'herramientas-jardin',
      price: 18500,
      stock: 45,
      skuPrefix: 'VIV-SET-HRR',
      description: 'Aluminio fundido macizo antioxidable con mango ergonómico de goma antideslizante.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Pulverizador Rociador a Presión Previa 2 Litros con Válvula',
      categorySlug: 'herramientas-jardin',
      price: 16000,
      stock: 50,
      skuPrefix: 'VIV-PUL-2L',
      description: 'Boquilla de bronce regulable desde chorro directo hasta niebla ultrafina con traba de gatillo.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
    {
      name: 'Guantes de Jardinería con Palma de Nitrilo Antiespinas',
      categorySlug: 'herramientas-jardin',
      price: 7900,
      stock: 80,
      skuPrefix: 'VIV-GNT-JAR',
      description: 'Tejido elástico transpirable con recubrimiento impermeable que protege contra cortes y humedad.',
      image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop&q=80',
      hasVariants: false,
    },
  ],
};
